In [1]:
import pandas as pd

personality_data = pd.read_csv("data/Lab 3 - Personality Profile Type.csv")
personality_data.head()

   type                                              posts
0  INFJ  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...
1  ENTP  'I'm finding the lack of me in these posts ver...
2  INTP  'Good one  _____   https://www.youtube.com/wat...
3  INTJ  'Dear INTP,   I enjoyed our conversation the o...
4  ENTJ  'You're fired.|||That's another silly misconce...

In [2]:
personality_data["type"].value_counts()

type
INFP    1832
INFJ    1470
INTP    1304
INTJ    1091
ENTP     685
ENFP     675
ISTP     337
ISFP     271
ENTJ     231
ISTJ     205
ENFJ     190
ISFJ     166
ESTP      89
ESFP      48
ESFJ      42
ESTJ      39
Name: count, dtype: int64

In [3]:
personality_data["type"].nunique()

16

In [4]:
import random
random_indicies = random.sample(range(len(personality_data)), 10)
for i in random_indicies:
    print(f"index: {i}\nType: {personality_data['type'][i]}\nPosts: {personality_data['posts'][i]}\n\n")

index: 8283
Type: INFJ
Posts: 'Is he willing to use public restrooms? I ask, because if it gets to the point where he avoids using any other bathroom altogether (like, he will hold everything in for hours until he is safe in his...|||I'm talking about between the ages of about six and thirteen...  A Story:   When I was in 4th Grade, my teacher got up in front of the class one morning and told us about an article she had just...|||well, if it's completely empty, then I'd have to take the dirver's seat to go anywhere...;)  If it's a given that there's already a driver, then I'd probably sit about three or four rows back on...|||Your Se was probably taking over in the moment...|||To clarify. Yes, the order of the functions in socionics is as you say. However, according to Model A, they are not ordered by strength. Functions 1, 2, 7, and 8 are the stronger functions; and 3, 4,...|||When you posted your song a while back and talked about how you could play by ear and taught yourself...I had the thought that you might be an ISFJ, since Si is the function that seems to be most...|||That's the one I used...|||I'm starting to figure this out myself...  My understanding so far is that-- based on Model A Socionics-- the four strongest functions for INFj are Fi, Ne, Ni, and Fe. The Thinking and Sensing...|||Umm, I'm taking a med for General Anxiety Disorder (have mentioned that before). Only four people in real life know that, and they're all family.  I still imagine monsters in the closet sometimes....|||homemade-quality bread  with butter...|||Actually, I believe you've got it backwards. A Ben> B, so ISFj (or ISFP) would be Benefactor to INFp (or INFJ)  A is Down and B is Across...    May be. I take it all with a grain of salt. I...|||So, if we're more like the Look-a-Like relation, does that mean that I could actually be an INFP? (because there is no way my husband is an ISFJ) Or can it just mean that I have very well-developed...|||First, I did get the right Types the first time. INFp=INFj and INTj=INTp. So, no confusion there :)  Actually, the look-a-like relationship does sound a lot like my husband and me. The comparative,...|||My husband and I definitely fit the bolded qualification. And, of course we are also attracted to each other (obviously, hehe).   So, the Relation of Benefit is apparently what we have, me being...|||source: Relations of Benefit between psychological (personality) types|||I can't say with confidence that I would be able to wake up without an alarm clock. But, during the day I usually have a pretty good idea what time it is at any given time, within a 10-minute margin...|||My husband and I have recently been trying to figure out the types of his sisters, who are twins. We've come to the tentative conclusion that they must be the same Type, but having taken on opposite...|||Those of you who have worked fast food-- or other similar jobs-- what was it like?  So, I had a job the summer after high school working at a fast food place before I went off to college. It didn't...|||Not at all. And I meant no offense to you.  All in good fun?  :D|||Ah, but if I'm being passive-aggressive, then by definition, so are you :tongue::wink:|||Okay, sorry...I only mentioned my roommate in response to the controversry you mentioned in your OP. You're the one who opened up the discussion of Aspergers and Type, my friend.   So, what do you...|||idk, but I had a roommate in college with Aspergers, and she very well could have been an INFJ...|||Sorry I haven't read all the posts in this thread. But finding the term, out-of-the-box several times while skimming through, got me recalling some of the out-of-the-box ideas I've had in the...|||Well, it's certainly not Ne...If I were using Ne in those situations, then wouldn't I be making more of a diligent effort to consider all my options and want to try a little bit of everything all at...|||I was shy as a kid, but I'm not really anymore. Though I am still reserved about certain things...like, I'm not likely to be one to get up and do a crazy dance in front of a bunch of people. But I am...|||Just...WOW. There couldn't be a better description out there of what it has been like for me as a mother. Especially since Baby #2 arrived. I'd quote the OP and bold parts that particularly apply to...|||If you do a Google search on Blessing Cleansing your Home, you will get some ideas...I guess, the nature of the cleanse depends on your own personal philosophy/religion and what you want to have...|||Me neither. Though I like writing song lyrics once in a while, and I have written a few (and a few really does mean a few) poems as inspired. Prose is really my thing. And dialog; I love plays....|||I like some cool stuff...like SWORDS, and LASERS, and SPACESHIPS, and MAGIC, and and and...  :laughing:  Nope, not into cars and motorcycles and airplanes...unless they FLY! well, I guess...|||I write endings a lot better than anything else. I can always see where I want to go in a story, but following a linear path to get there proves daunting. I write snippets, scenes, conversations,...|||INJ Traits They have vivid imaginations  They're curious about everything, and are always asking Why?  They enjoy spending time one-on-one with others, rather than in large groups  They're...|||Creative Writing...I will get a good idea and write excitedly...and then I will hit a wall mentally and can go no further. I wait and wait and wait for further inspiration to come, and if it comes, I...|||I like the OP's groupings. Just found this: Personality and Kids which asserts that the first two letters to be determined in a young child's personality types are I/E and P/J, so...the suggestion to...|||I am guilty of this, too...|||I do this, too...In MS and HS I used to read while I walked from one class to the next, and managed to never run into anyone else or anything else.  Also, when I'm alone (which is hardly ever...|||Whistle Blower? I'm sorry, but that just makes it sound like this guy (or gal?) is suggesting that we be tattle-tales. That...doesn't sit well with me...|||My INFJ mother-in-law apparently is like this a lot. She'll get into a cleaning frenzy and clean up the home office, including my husband's workspace (he works for the family business); he hates...|||So, an INFJ would be a Scionics IEI, right?  And here I thought I finally had the MBTI more or less figured out, now there's a whole other system for me to learn! Aaaahhhh!|||http://www.youtube.com/watch?v=cAbCNtk8sOM  Disillusioned Ni? lol|||Umm, he sounds like he has some pretty serious anitsocial issues...Why won't he go anywhere? What is he afraid of? Has he been hurt in the past? Does he really like it when people make fun of him, or...|||I am surely guilty of this, too. When I'm stressed, I start to doubt my Ni and start using Ne instead, but then afterward I realize it was all pointless, that I should have just listened to what my...|||Have you looked at INTJ and INTP?|||Soul searcher, just curious: what Type do you think your Mom is/was? I think mine is ISFJ...|||This part definitely makes you sound like an INFJ. The desire to help people, and to improve society according to our own personal vision, seems to be a hallmark of INFJs. For instance, I want to be...|||When I was in college, I would try to show up to lectures 15-20 minutes early so I could just have some quiet time to read, study, or just close my eyes and rest for a little while. I still have a...|||I'm with the majority so far. I would love to have a home with a good chunk of natural land, but no more than 20 minutes from the city (not a majorly big city, though; I think we have like, 20,000+...|||This is me, too. But I've had to start making myself say no more, to take care of my health. It's hard, though.|||The people I am closest to right now, that I spend time with at least 2 times a week or more, are my husband and kids, my mother- and father-in-law, and my brother-in-law and his wife and kids.  On...|||I know I can't for-sure type my kid yet (didn't I say that in my OP?). That doesn't mean he can't already be displaying some marked preferences for certain functions, even though those preferences...|||So, my son is only 3 and a half years old, but of all the personality types so far, ENTP is the one that seems to fit him best. I realize this can change in the future, since I understand...'


index: 36
Type: INTJ
Posts: 'Poker face for sure, accompanied by some sarcasm probably! But inside I'm running a pretty vivid list of pros and cons starting with asking myself 'do I like them back'? I probably know the answer...|||1. Babies are illogical. 2. Nobody is despised who can manage a crocodile. 3. Illogical persons are despised. Therefore, babies cannot manage crocodiles.  1. No interesting poems are unpopular...|||Well yeah, zero sounds legitimate, but I've found for myself that there are other life forms besides me, who are quite interesting and worth a chance, at least one chance and I tend to give them...|||That's why you shouldn't explain to everybody but just the ones you care about and want to keep around :wink:|||I went in, did my thing and got out and picked up few really valuable friendships from each uni.  Never though that this had to be the best time of my life. It wasn't bad but also not the best....|||Don't know about others but for me such questions are really annoying and mostly I do ask back what do you mean (because I really don't understand what is wanted) or why do you need to know that...|||http://digidragons.com/CM/Hug.gif|||I try to believe like I believed when I was five... when your heart tells you everything you need to know. - Lucy Liu -  Everything we hear is an opinion, not a fact. Everything we see is a...|||- Relaxed - Honest - Sincere - Reliable - Strong  Can be lot of other things also, among them fun and childish, but wouldn't say these are my main qualities. Everything depends on a situation...|||Exactly, what's normal to me might not be for someone else and vice versa.  My grammar should bother you indeed, English is not my first language, more like 4th. I'm surprised I can read or write...|||I've been thinking about the detached part also cos I don't feel detached at all, I actually tend to see others much more detached compared to me. Maybe it comes down to priorities and what's...|||- Lack of common sense, intelligence and personal hygiene; - Sloppiness when attention to detail is needed; - When it takes forever to get a point across, speed of mind is a must; - Wasting my...|||Not using my time effectively (that is according to me), otherwise I've never been afraid and won't start now!|||When I was a kid I loved taking things apart, not breaking but carefully investigating how stuff works. Sometimes managed to put it back together also... Later on it was the money aspect of life...|||I've been trying to enlighten the ones closest to me by asking them to take some tests and afterwards explaining, that see, ppl are different and I happen to see things and situations bit differently...|||I know the feeling, even if I know they know me and won't mind, I still feel bad sometimes. So I'll contact them myself and there will be some forced awkward conversation... till I actually find...|||Felt like :shocked: and printing it out to spread the knowledge, like - see, it's not a syndrome! :happy:  But for real, felt like autopsy. Wasn't sure should I cry or laugh. By now I'm ok with...|||Every now and then some new ppl appear into your life and they have no clue regarding your preferences. Most of them will disappear shortly with the knowledge that you are one rude person, but some...|||https://scontent-b-ams.xx.fbcdn.net/hphotos-xap1/v/t1.0-9/10710579_10152812166261840_5647117484909782143_n.jpg?oh=1528a3178b6df4ddbf4a5e971b74dd6e&oe=54E8A584|||You are welcome! Of course you will miss them, but not 24/7, more like once every few months if you don't see them at all. If you will still be in the same country/city and see them more then once a...|||I've been on my own since 16. Long messy story, but if I'd have to do it again then wouldn't change a thing! The sooner you figure out what makes you tick the more you get out of your life and people...|||Love is a many splendored thing. Love lifts us up where we belong. All you need is love! :happy:  Supposedly there's only 2 emotions - love and fear - and all feelings go back to either one or...|||Been called this and that but yeah, never hypocritical and I kind of like it. In my mind ppl just can't handle the truth and then give labels like arrogant. When I was younger I struggled quite a bit...|||I've thought about it a lot and there's nothing I can do to force myself into something which just isn't what I want. I've had enough relationships (short and long ones) to understand, that I'll...|||I'm quite ignorant when it comes to whatever issues I may have this includes being sick. I somehow feel I'm above everything that should hurt me and nothing can possibly take me down. Of course then...|||Scared? :laughing: No! :ninja: And of course I can feel stuff.|||Nothing against rational compromise. Criteria for a fair one would be that the compromise is equal for both sides, both should feel they made a fair trade so to say. Different people have different...|||Can't live without music. My first cassette (yes that was some time ago) had Nirvana on one side and Mozart on the other, I listened to it days and nights with my light blue Walkman :happy: After...|||View photos on a computer in secret https://scontent-a.xx.fbcdn.net/hphotos-ash2/v/t1.0-9/548932_10151520239861141_811356832_n.jpg?oh=cb487b288395f8634c9b5721cdc50436&oe=54C8EC5D ...|||Quite long but worth it I think: Email exchange between parent and school chaplain.|||You might be onto something here :laughing:|||When somebody who I respect and see as level above me intelligence wise tells me job well done then it means more to me than 10 non-experts saying omg, u r the best ever... even if they are...|||Makes me laugh cos I can relate and if I can't relate then I can easily imagine the situation. Sometimes in a perfectly serious situation I get these ridiculous bursts of laughter internally cos  for...|||Sounds legitimate!|||Logical enough.   https://www.youtube.com/watch?v=MDpyS2HN5SA|||You may want to check this thread out :happy: Looks like we're lazy as hell. But I guess that's one of the reasons we're also efficient or it looks like we are. For example it is so very hard for me...|||Sustaining any kind of routine without some sort of visible end point is quite challenging I've found. But I do have a strong drive in me to deliver (probably just to prove myself I'm able to do it)...|||I use to take it really seriously and the reactions were more devastating then they maybe should of been (probably has to do also with my personal story/history). Now I mostly walk away cos there's...|||:laughing: At some point I actually felt that I am being arrogant to think that only I can take that thing where it's suppose to be. But with time I've seen that in most cases that's exactly how...|||Why unfortunately? It's really not that much fun as it may look like :laughing:|||The only theory that amazed me actually was graphology, I couldn't believe how accurate it was regarding the stuff that's inside me! As a result changed some letters... I was amazed because all...|||Well :laughing: I have strong faith only in myself. I'm just really curious when it comes to all kinds of systems and since I so very much want to understand myself (why I feel and act the way I do,...|||Yes but in most cases the only way to tell do I have any feelings for someone would be to see inside my head/heart. You'd have to know me pretty well to understand that something is going on. I can...|||You like INTJs probably cos Sag is also pretty blunt and often times has no clue why ppl around them can't take the truth (well their view of it anyway) :happy:  Also Sag and 5 give you the need for...|||199706 199714  199722 199730  199738|||How do you want to be seen by others or society, to the degree? I want to be seen as I am - sincere unlimited being.  What kind of role do you want to play in others' lives? Roles..., I've been...|||Somebody once told me I'd make a damn good criminal but I'll always choose the cops side. Thinking like them helps to catch them, so why not know exactly how and why, which doesn't mean I'll act like...|||Well put. There's very few people who understand completely when I'm trying to explain something which consists several parts. In my mind I see it all nice and clear and working like it should but as...|||I think she's not kidding if she's INTJ. If I say out loud go away, then for sure I'm not kidding. Just explaining my view now cos that's the only view I can explain, not sure do all INTJ females...|||For sure ISFP suits much better with Sag and 11 :happy: I come off as this quite clever but arrogant, blunt, emotionless thing. I guess it's a good shield to keep unwanted away. There's plenty...'


index: 4554
Type: INFJ

In [5]:
personality_data.duplicated().sum()

np.int64(0)

In [6]:
personality_data.isnull().sum()

type     0
posts    0
dtype: int64

In [7]:
personality_data["type"].value_counts(normalize=True)*100

type
INFP    21.118156
INFJ    16.945245
INTP    15.031700
INTJ    12.576369
ENTP     7.896254
ENFP     7.780980
ISTP     3.884726
ISFP     3.123919
ENTJ     2.662824
ISTJ     2.363112
ENFJ     2.190202
ISFJ     1.913545
ESTP     1.025937
ESFP     0.553314
ESFJ     0.484150
ESTJ     0.449568
Name: proportion, dtype: float64

* IDK if this is a good approach but i see data rows isnt much yet the text that will be given to rnn is massive
* i realize that for each row its about posts and depend on all the posts in understand type of user
* i will split data on the ||| and for each of them new row with the same output will increase number of rows to train model on and in same time limit number of text entering the GRU model i will build later for memory loss controll

In [8]:
personality_data["posts"] = personality_data["posts"].apply(lambda x: str(x).split("|||"))
exploded_data = personality_data.explode("posts").reset_index(drop=True)
exploded_data.head()

   type                                              posts
0  INFJ        'http://www.youtube.com/watch?v=qsXHcwe3krw
1  INFJ  http://41.media.tumblr.com/tumblr_lfouy03PMA1q...
2  INFJ  enfp and intj moments  https://www.youtube.com...
3  INFJ  What has been the most life-changing experienc...
4  INFJ  http://www.youtube.com/watch?v=vXZeYwwRDw8   h...

In [9]:
exploded_data.shape

(422845, 2)

In [10]:
for row in exploded_data.itertuples():
	if row.posts is None or str(row.posts).strip() == "":
		print(f"index: {row.Index}\nType: {row.type}\nPosts: '{row.posts}'\n\n")

index: 2711
Type: INFP
Posts: ''


index: 2713
Type: INFP
Posts: ''


index: 2715
Type: INFP
Posts: ''


index: 2716
Type: INFP
Posts: ''


index: 2717
Type: INFP
Posts: ''


index: 8085
Type: INTJ
Posts: ''


index: 8086
Type: INTJ
Posts: ''


index: 8087
Type: INTJ
Posts: ''


index: 8088
Type: INTJ
Posts: ''


index: 8090
Type: INTJ
Posts: ''


index: 8091
Type: INTJ
Posts: ''


index: 8092
Type: INTJ
Posts: ''


index: 8094
Type: INTJ
Posts: ''


index: 8095
Type: INTJ
Posts: ''


index: 8096
Type: INTJ
Posts: ''


index: 9725
Type: ESFP
Posts: ''


index: 9726
Type: ESFP
Posts: ''


index: 10085
Type: INTP
Posts: ''


index: 10087
Type: INTP
Posts: ''


index: 10088
Type: INTP
Posts: ''


index: 10089
Type: INTP
Posts: ''


index: 14322
Type: ENTP
Posts: ''


index: 14323
Type: ENTP
Posts: ''


index: 14324
Type: ENTP
Posts: ''


index: 14325
Type: ENTP
Posts: ''


index: 14326
Type: ENTP
Posts: ''


index: 14328
Type: ENTP
Posts: ''


index: 14330
Type: ENTP
Posts: ''


index: 14331
Type: ENTP
Posts: ''


index: 14332
Type: ENTP
Posts: ''


index: 14333
Type: ENTP
Posts: ''


index: 18855
Type: ENTJ
Posts: ''


index: 18856
Type: ENTJ
Posts: ''


index: 18857
Type: ENTJ
Posts: ''


index: 18858
Type: ENTJ
Posts: ''


index: 18860
Type: ENTJ
Posts: ''


index: 18861
Type: ENTJ
Posts: ''


index: 18880
Type: ENTJ
Posts: ''


index: 18917
Type: ENFP
Posts: ''


index: 18918
Type: ENFP
Posts: ''


index: 18919
Type: ENFP
Posts: ''


index: 18920
Type: ENFP
Posts: ''


index: 18921
Type: ENFP
Posts: ''


index: 18922
Type: ENFP
Posts: ''


index: 18923
Type: ENFP
Posts: ''


index: 18933
Type: ENFP
Posts: ''


index: 18934
Type: ENFP
Posts: ''


index: 18935
Type: ENFP
Posts: ''


index: 18936
Type: ENFP
Posts: ''


index: 18937
Type: ENFP
Posts: ''


index: 18938
Type: ENFP
Posts: ''


index: 18939
Type: ENFP
Posts: ''


index: 23092
Type: ISTP
Posts: ''


index: 23093
Type: ISTP
Posts: ''


index: 24539
Type: INTJ
Posts: ''


index: 24540
Type: INTJ
Posts: ''


index: 24541
Type: INTJ
Posts: ''


index: 24543
Type: INTJ
Posts: ''


index: 24544
Type: INTJ
Posts: ''


index: 24545
Type: INTJ
Posts: ''


index: 24546
Type: INTJ
Posts: ''


index: 34044
Type: INFP
Posts: ''


index: 36066
Type: ENTP
Posts: ''


index: 36067
Type: ENTP
Posts: ''


index: 36068
Type: ENTP
Posts: ''


index: 36069
Type: ENTP
Posts: ''


index: 36070
Type: ENTP
Posts: ''


index: 36071
Type: ENTP
Posts: ''


index: 36072
Type: ENTP
Posts: ''


index: 36686
Type: INFJ
Posts: ''


index: 36687
Type: INFJ
Posts: ''


index: 36688
Type: INFJ
Posts: ''


index: 36690
Type: INFJ
Posts: ''


index: 36691
Type: INFJ
Posts: ''


index: 37299
Type: INFJ
Posts: ''


index: 37300
Type: INFJ
Posts: ''


index: 37301
Type: INFJ
Posts: ''


index: 37303
Type: INFJ
Posts: ''


index: 37304
Type: INFJ
Posts: ''


index: 37305
Type: INFJ
Posts: ''


index: 37306
Type: INFJ
Posts: ''


index: 37308
Type: INFJ
Posts: ''


index: 37309
Type: INFJ
Posts: ''


index: 37310
Type: INFJ
Posts: ''


index: 37311
Type: INFJ
Posts: ''


index: 37312
Type: INFJ
Posts: ''


index: 37314
Type: INFJ
Posts: ''


index: 37315
Type: INFJ
Posts: ''


index: 37316
Type: INFJ
Posts: ''


index: 42822
Type: INTJ
Posts: ''


index: 42823
Type: INTJ
Posts: ''


index: 42824
Type: INTJ
Posts: ''


index: 42825
Type: INTJ
Posts: ''


index: 42827
Type: INTJ
Posts: ''


index: 42828
Type: INTJ
Posts: ''


index: 42829
Type: INTJ
Posts: ''


index: 42831
Type: INTJ
Posts: ''


index: 44276
Type: ENTP
Posts: ''


index: 44278
Type: ENTP
Posts: ''


index: 44279
Type: ENTP
Posts: ''


index: 44280
Type: ENTP
Posts: ''


index: 44282
Type: ENTP
Posts: ''


index: 44283
Type: ENTP
Posts: ''


index: 44284
Type: ENTP
Posts: ''


index: 44285
Type: ENTP
Posts: ''


index: 44286
Type: ENTP
Posts: ''


index: 44288
Type: ENTP
Posts: ''


index: 44289
Type: ENTP
Posts: ''


index: 44290
Type: ENTP
Posts: ''


index: 44293
Type: ENTP
Posts: ''


index: 52047
Type: INFP
Posts: ''


index: 52049
Type: INFP
Posts: ''


index: 52051
Type: INFP
Posts: ''


index: 52052
Type: INFP
Posts: ''


index: 52053
Type: INFP
Posts: ''


index: 52054
Type: INFP
Posts: ''


index: 52056
Type: INFP
Posts: ''


index: 52057
Type: INFP
Posts: ''


index: 52058
Type: INFP
Posts: ''


index: 52059
Type: INFP
Posts: ''


index: 52060
Type: INFP
Posts: ''


index: 52062
Type: INFP
Posts: ''


index: 52065
Type: INFP
Posts: ''


index: 52066
Type: INFP
Posts: ''


index: 52067
Type: INFP
Posts: ''


index: 52068
Type: INFP
Posts: ''


index: 52069
Type: INFP
Posts: ''


index: 52071
Type: INFP
Posts: ''


index: 52072
Type: INFP
Posts: ''


index: 52073
Type: INFP
Posts: ''


index: 52074
Type: INFP
Posts: ''


index: 52526
Type: INFP
Posts: ''


index: 52527
Type: INFP
Posts: ''


index: 52529
Type: INFP
Posts: ''


index: 52530
Type: INFP
Posts: ''


index: 54012
Type: INTP
Posts: ''


index: 54014
Type: INTP
Posts: ''


index: 54015
Type: INTP
Posts: ''


index: 54016
Type: INTP
Posts: ''


index: 54018
Type: INTP
Posts: ''


index: 54019
Type: INTP
Posts: ''


index: 54020
Type: INTP
Posts: ''


index: 54021
Type: INTP
Posts: ''


index: 54023
Type: INTP
Posts: ''


index: 54025
Type: INTP
Posts: ''


index: 54026
Type: INTP
Posts: ''


index: 54027
Type: INTP
Posts: ''


index: 54028
Type: INTP
Posts: ''


index: 54029
Type: INTP
Posts: ''


index: 54344
Type: ENTJ
Posts: ''


index: 54345
Type: ENTJ
Posts: ''


index: 54346
Type: ENTJ
Posts: ''


index: 54347
Type: ENTJ
Posts: ''


index: 54348
Type: ENTJ
Posts: ''


index: 55945
Type: INTP
Posts: ''


index: 55946
Type: INTP
Posts: ''


index: 55947
Type: INTP
Posts: ''


index: 55948
Type: INTP
Posts: ''


index: 55949
Type: INTP
Posts: ''


index: 55950
Type: INTP
Posts: ''


index: 55951
Type: INTP
Posts: ''


index: 55953
Type: INTP
Posts: ''


index: 55954
Type: INTP
Posts: ''


index: 55955
Type: INTP
Posts: ''


index: 55956
Type: INTP
Posts: ''


index: 55957
Type: INTP
Posts: ''


index: 55958
Type: INTP
Posts: ''


index: 55960
Type: INTP
Posts: ''


index: 55961
Type: INTP
Posts: ''


index: 55962
Type: INTP
Posts: ''


index: 55963
Type: INTP
Posts: ''


index: 56614
Type: ENTP
Posts: ''


index: 56615
Type: ENTP
Posts: ''


index: 56616
Type: ENTP
Posts: ''


index: 56617
Type: ENTP
Posts: ''


index: 56618
Type: ENTP
Posts: ''


index: 56620
Type: ENTP
Posts: ''


index: 56621
Type: ENTP
Posts: ''


index: 56622
Type: ENTP
Posts: ''


index: 56624
Type: ENTP
Posts: ''


index: 56625
Type: ENTP
Posts: ''


index: 56626
Type: ENTP
Posts: ''


index: 56628
Type: ENTP
Posts: ''


index: 56629
Type: ENTP
Posts: ''


index: 56630
Type: ENTP
Posts: ''


index: 56631
Type: ENTP
Posts: ''


index: 56632
Type: ENTP
Posts: ''


index: 56634
Type: ENTP
Posts: ''


index: 56635
Type: ENTP
Posts: ''


index: 56637
Type: ENTP
Posts: ''


index: 59060
Type: ENFP
Posts: ''


index: 59061
Type: ENFP
Posts: ''


index: 59062
Type: ENFP
Posts: ''


index: 59064
Type: ENFP
Posts: ''


index: 59065
Type: ENFP
Posts: ''


index: 59066
Type: ENFP
Posts: ''


index: 59068
Type: ENFP
Posts: ''


index: 59069
Type: ENFP
Posts: ''


index: 59070
Type: ENFP
Posts: ''


index: 59071
Type: ENFP
Posts: ''


index: 59072
Type: ENFP
Posts: ''


index: 59074
Type: ENFP
Posts: ''


index: 59075
Type: ENFP
Posts: ''


index: 59076
Type: ENFP
Posts: ''


index: 59177
Type: ENTP
Posts: ''


index: 59178
Type: ENTP
Posts: ''


index: 59179
Type: ENTP
Posts: ''


index: 59180
Type: ENTP
Posts: ''


index: 59182
Type: ENTP
Posts: ''


index: 59183
Type: ENTP
Posts: ''


index: 59184
Type: ENTP
Posts: ''


index: 59185
Type: ENTP
Posts: ''


index: 59186
Type: ENTP
Posts: ''


index: 59187
Type: ENTP
Posts: ''


index: 59189
Type: ENTP
Posts: ''


index: 59190
Type: ENTP
Posts: ''


index: 59191
Type: ENTP
Posts: ''


index: 59192
Type: ENTP
Posts: ''


index: 59193
Type: ENTP
Posts: ''


index: 59194
Type: ENTP
Posts: ''


index: 59586
Type: INFJ
Posts: ''


index: 59587
Type: INFJ
Posts: ''


index: 59589
Type: INFJ
Posts: ''


index: 59590
Type: INFJ
Posts: ''


index: 59591
Type: INFJ
Posts: ''


index: 59593
Type: INFJ
Posts: ''


index: 59594
Type: INFJ
Posts: ''


index: 59596
Type: INFJ
Posts: ''


index: 59597
Type: INFJ
Posts: ''


index: 59598
Type: INFJ
Posts: ''


index: 59600
Type: INFJ
Posts: ''


index: 59601
Type: INFJ
Posts: ''


index: 59602
Type: INFJ
Posts: ''


index: 59603
Type: INFJ
Posts: ''


index: 66306
Type: INFP
Posts: ''


index: 67911
Type: ENFP
Posts: ''


index: 67913
Type: ENFP
Posts: ''


index: 67915
Type: ENFP
Posts: ''


index: 67916
Type: ENFP
Posts: ''


index: 67917
Type: ENFP
Posts: ''


index: 67919
Type: ENFP
Posts: ''


index: 67920
Type: ENFP
Posts: ''


index: 67921
Type: ENFP
Posts: ''


index: 67922
Type: ENFP
Posts: ''


index: 67923
Type: ENFP
Posts: ''


index: 67925
Type: ENFP
Posts: ''


index: 67926
Type: ENFP
Posts: ''


index: 67927
Type: ENFP
Posts: ''


index: 67928
Type: ENFP
Posts: ''


index: 67930
Type: ENFP
Posts: ''


index: 67931
Type: ENFP
Posts: ''


index: 67933
Type: ENFP
Posts: ''


index: 67934
Type: ENFP
Posts: ''


index: 67935
Type: ENFP
Posts: ''


index: 67936
Type: ENFP
Posts: ''


index: 67937
Type: ENFP
Posts: ''


index: 67939
Type: ENFP
Posts: ''


index: 67940
Type: ENFP
Posts: ''


index: 67941
Type: ENFP
Posts: ''


index: 67942
Type: ENFP
Posts: ''


index: 70948
Type: ENTP
Posts: ''


index: 70949
Type: ENTP
Posts: ''


index: 70950
Type: ENTP
Posts: ''


index: 70951
Type: ENTP
Posts: ''


index: 70952
Type: ENTP
Posts: ''


index: 70953
Type: ENTP
Posts: ''


index: 70955
Type: ENTP
Posts: ''


index: 70956
Type: ENTP
Posts: ''


index: 70957
Type: ENTP
Posts: ''


index: 70958
Type: ENTP
Posts: ''


index: 75012
Type: INTJ
Posts: ''


index: 75014
Type: INTJ
Posts: ''


index: 75015
Type: INTJ
Posts: ''


index: 75016
Type: INTJ
Posts: ''


index: 75017
Type: INTJ
Posts: ''


index: 75018
Type: INTJ
Posts: ''


index: 80874
Type: INTJ
Posts: ''


index: 80875
Type: INTJ
Posts: ''


index: 80877
Type: INTJ
Posts: ''


index: 80878
Type: INTJ
Posts: ''


index: 80880
Type: INTJ
Posts: ''


index: 80881
Type: INTJ
Posts: ''


index: 80882
Type: INTJ
Posts: ''


index: 80883
Type: INTJ
Posts: ''


index: 80884
Type: INTJ
Posts: ''


index: 80886
Type: INTJ
Posts: ''


index: 80887
Type: INTJ
Posts: ''


index: 80888
Type: INTJ
Posts: ''


index: 80889
Type: INTJ
Posts: ''


index: 80892
Type: INTJ
Posts: ''


index: 84022
Type: ENTP
Posts: ''


index: 84025
Type: ENTP
Posts: ''


index: 84026
Type: ENTP
Posts: ''


index: 84029
Type: ENTP
Posts: ''


index: 84034
Type: ENTP
Posts: ''


index: 84037
Type: ENTP
Posts: ''


index: 84038
Type: ENTP
Posts: ''


index: 84473
Type: INFP
Posts: ''


index: 84475
Type: INFP
Posts: ''


index: 84477
Type: INFP
Posts: ''


index: 84478
Type: INFP
Posts: ''


index: 84479
Type: INFP
Posts: ''


index: 85993
Type: INFP
Posts: ''


index: 85995
Type: INFP
Posts: ''


index: 85997
Type: INFP
Posts: ''


index: 85998
Type: INFP
Posts: ''


index: 85999
Type: INFP
Posts: ''


index: 86001
Type: INFP
Posts: ''


index: 86002
Type: INFP
Posts: ''


index: 86003
Type: INFP
Posts: ''


index: 86004
Type: INFP
Posts: ''


index: 86006
Type: INFP
Posts: ''


index: 86007
Type: INFP
Posts: ''


index: 86008
Type: INFP
Posts: ''


index: 86010
Type: INFP
Posts: ''


index: 86012
Type: INFP
Posts: ''


index: 86013
Type: INFP
Posts: ''


index: 86014
Type: INFP
Posts: ''


index: 86015
Type: INFP
Posts: ''


index: 86016
Type: INFP
Posts: ''


index: 86018
Type: INFP
Posts: ''


index: 86019
Type: INFP
Posts: ''


index: 86020
Type: INFP
Posts: ''


index: 86021
Type: INFP
Posts: ''


index: 92021
Type: INTJ
Posts: ''


index: 92022
Type: INTJ
Posts: ''


index: 92023
Type: INTJ
Posts: ''


index: 92024
Type: INTJ
Posts: ''


index: 92025
Type: INTJ
Posts: ''


index: 92027
Type: INTJ
Posts: ''


index: 92028
Type: INTJ
Posts: ''


index: 92029
Type: INTJ
Posts: ''


index: 92030
Type: INTJ
Posts: ''


index: 92031
Type: INTJ
Posts: ''


index: 92033
Type: INTJ
Posts: ''


index: 92034
Type: INTJ
Posts: ''


index: 92035
Type: INTJ
Posts: ''


index: 92036
Type: INTJ
Posts: ''


index: 94108
Type: ENTP
Posts: ''


index: 94109
Type: ENTP
Posts: ''


index: 94110
Type: ENTP
Posts: ''


index: 94111
Type: ENTP
Posts: ''


index: 94112
Type: ENTP
Posts: ''


index: 94113
Type: ENTP
Posts: ''


index: 94114
Type: ENTP
Posts: ''


index: 94116
Type: ENTP
Posts: ''


index: 94117
Type: ENTP
Posts: ''


index: 94118
Type: ENTP
Posts: ''


index: 94120
Type: ENTP
Posts: ''


index: 94121
Type: ENTP
Posts: ''


index: 94122
Type: ENTP
Posts: ''


index: 94123
Type: ENTP
Posts: ''


index: 94124
Type: ENTP
Posts: ''


index: 96716
Type: ISTJ
Posts: ''


index: 96717
Type: ISTJ
Posts: ''


index: 96718
Type: ISTJ
Posts: ''


index: 96719
Type: ISTJ
Posts: ''


index: 96721
Type: ISTJ
Posts: ''


index: 96722
Type: ISTJ
Posts: ''


index: 96723
Type: ISTJ
Posts: ''


index: 96724
Type: ISTJ
Posts: ''


index: 96725
Type: ISTJ
Posts: ''


index: 99065
Type: ISFP
Posts: ''


index: 99066
Type: ISFP
Posts: ''


index: 99067
Type: ISFP
Posts: ''


index: 99069
Type: ISFP
Posts: ''


index: 99070
Type: ISFP
Posts: ''


index: 99071
Type: ISFP
Posts: ''


index: 99073
Type: ISFP
Posts: ''


index: 99074
Type: ISFP
Posts: ''


index: 99075
Type: ISFP
Posts: ''


index: 99076
Type: ISFP
Posts: ''


index: 99077
Type: ISFP
Posts: ''


index: 99738
Type: INFP
Posts: ''


index: 99739
Type: INFP
Posts: ''


index: 99741
Type: INFP
Posts: ''


index: 99742
Type: INFP
Posts: ''


index: 99743
Type: INFP
Posts: ''


index: 99744
Type: INFP
Posts: ''


index: 99745
Type: INFP
Posts: ''


index: 99747
Type: INFP
Posts: ''


index: 99748
Type: INFP
Posts: ''


index: 99749
Type: INFP
Posts: ''


index: 99750
Type: INFP
Posts: ''


index: 99751
Type: INFP
Posts: ''


index: 99754
Type: INFP
Posts: ''


index: 99755
Type: INFP
Posts: ''


index: 99756
Type: INFP
Posts: ''


index: 99757
Type: INFP
Posts: ''


index: 99758
Type: INFP
Posts: ''


index: 100823
Type: INFP
Posts: ''


index: 104136
Type: ENTP
Posts: ''


index: 104138
Type: ENTP
Posts: ''


index: 104139
Type: ENTP
Posts: ''


index: 104140
Type: ENTP
Posts: ''


index: 104141
Type: ENTP
Posts: ''


index: 104142
Type: ENTP
Posts: ''


index: 105858
Type: INFP
Posts: ''


index: 105859
Type: INFP
Posts: ''


index: 105860
Type: INFP
Posts: ''


index: 105862
Type: INFP
Posts: ''


index: 105863
Type: INFP
Posts: ''


index: 105864
Type: INFP
Posts: ''


index: 105866
Type: INFP
Posts: ''


index: 105867
Type: INFP
Posts: ''


index: 105868
Type: INFP
Posts: ''


index: 105869
Type: INFP
Posts: ''


index: 105871
Type: INFP
Posts: ''


index: 105872
Type: INFP
Posts: ''


index: 105873
Type: INFP
Posts: ''


index: 105901
Type: INFP
Posts: ''


index: 105902
Type: INFP
Posts: ''


index: 110450
Type: INFP
Posts: ''


index: 110452
Type: INFP
Posts: ''


index: 110454
Type: INFP
Posts: ''


index: 110455
Type: INFP
Posts: ''


index: 110456
Type: INFP
Posts: ''


index: 110457
Type: INFP
Posts: ''


index: 110458
Type: INFP
Posts: ''


index: 124388
Type: ISFP
Posts: ''


index: 124389
Type: ISFP
Posts: ''


index: 124390
Type: ISFP
Posts: ''


index: 124391
Type: ISFP
Posts: ''


index: 124392
Type: ISFP
Posts: ''


index: 126224
Type: INFJ
Posts: ''


index: 126225
Type: INFJ
Posts: ''


index: 126226
Type: INFJ
Posts: ''


index: 126228
Type: INFJ
Posts: ''


index: 126229
Type: INFJ
Posts: ''


index: 126231
Type: INFJ
Posts: ''


index: 126233
Type: INFJ
Posts: ''


index: 126234
Type: INFJ
Posts: ''


index: 126235
Type: INFJ
Posts: ''


index: 140568
Type: ESTJ
Posts: ''


index: 140569
Type: ESTJ
Posts: ''


index: 140571
Type: ESTJ
Posts: ''


index: 140572
Type: ESTJ
Posts: ''


index: 140573
Type: ESTJ
Posts: ''


index: 141716
Type: ENTP
Posts: ''


index: 141717
Type: ENTP
Posts: ''


index: 141718
Type: ENTP
Posts: ''


index: 141720
Type: ENTP
Posts: ''


index: 141721
Type: ENTP
Posts: ''


index: 142947
Type: ENFP
Posts: ''


index: 142948
Type: ENFP
Posts: ''


index: 142950
Type: ENFP
Posts: ''


index: 142951
Type: ENFP
Posts: ''


index: 142952
Type: ENFP
Posts: ''


index: 142954
Type: ENFP
Posts: ''


index: 142955
Type: ENFP
Posts: ''


index: 142957
Type: ENFP
Posts: ''


index: 142958
Type: ENFP
Posts: ''


index: 142959
Type: ENFP
Posts: ''


index: 144531
Type: ENTP
Posts: ''


index: 144533
Type: ENTP
Posts: ''


index: 144534
Type: ENTP
Posts: ''


index: 144535
Type: ENTP
Posts: ''


index: 144536
Type: ENTP
Posts: ''


index: 144538
Type: ENTP
Posts: ''


index: 144539
Type: ENTP
Posts: ''


index: 144540
Type: ENTP
Posts: ''


index: 144541
Type: ENTP
Posts: ''


index: 144542
Type: ENTP
Posts: ''


index: 144544
Type: ENTP
Posts: ''


index: 144545
Type: ENTP
Posts: ''


index: 144546
Type: ENTP
Posts: ''


index: 144548
Type: ENTP
Posts: ''


index: 144550
Type: ENTP
Posts: ''


index: 144551
Type: ENTP
Posts: ''


index: 148544
Type: ISTJ
Posts: ''


index: 148545
Type: ISTJ
Posts: ''


index: 148546
Type: ISTJ
Posts: ''


index: 148547
Type: ISTJ
Posts: ''


index: 148549
Type: ISTJ
Posts: ''


index: 148550
Type: ISTJ
Posts: ''


index: 148551
Type: ISTJ
Posts: ''


index: 148552
Type: ISTJ
Posts: ''


index: 152758
Type: INFP
Posts: ''


index: 152759
Type: INFP
Posts: ''


index: 152760
Type: INFP
Posts: ''


index: 152761
Type: INFP
Posts: ''


index: 152762
Type: INFP
Posts: ''


index: 152763
Type: INFP
Posts: ''


index: 152764
Type: INFP
Posts: ''


index: 152765
Type: INFP
Posts: ''


index: 152767
Type: INFP
Posts: ''


index: 152768
Type: INFP
Posts: ''


index: 152769
Type: INFP
Posts: ''


index: 152770
Type: INFP
Posts: ''


index: 152771
Type: INFP
Posts: ''


index: 152772
Type: INFP
Posts: ''


index: 155508
Type: ENTP
Posts: ''


index: 155509
Type: ENTP
Posts: ''


index: 155510
Type: ENTP
Posts: ''


index: 155511
Type: ENTP
Posts: ''


index: 155512
Type: ENTP
Posts: ''


index: 155513
Type: ENTP
Posts: ''


index: 155515
Type: ENTP
Posts: ''


index: 155516
Type: ENTP
Posts: ''


index: 155517
Type: ENTP
Posts: ''


index: 155518
Type: ENTP
Posts: ''


index: 155519
Type: ENTP
Posts: ''


index: 155521
Type: ENTP
Posts: ''


index: 155522
Type: ENTP
Posts: ''


index: 155523
Type: ENTP
Posts: ''


index: 155524
Type: ENTP
Posts: ''


index: 155525
Type: ENTP
Posts: ''


index: 165375
Type: INFJ
Posts: ''


index: 165376
Type: INFJ
Posts: ''


index: 165377
Type: INFJ
Posts: ''


index: 165378
Type: INFJ
Posts: ''


index: 165379
Type: INFJ
Posts: ''


index: 165380
Type: INFJ
Posts: ''


index: 165381
Type: INFJ
Posts: ''


index: 165382
Type: INFJ
Posts: ''


index: 165384
Type: INFJ
Posts: ''


index: 165385
Type: INFJ
Posts: ''


index: 165386
Type: INFJ
Posts: ''


index: 165387
Type: INFJ
Posts: ''


index: 165388
Type: INFJ
Posts: ''


index: 165389
Type: INFJ
Posts: ''


index: 165390
Type: INFJ
Posts: ''


index: 165392
Type: INFJ
Posts: ''


index: 165393
Type: INFJ
Posts: ''


index: 165394
Type: INFJ
Posts: ''


index: 165395
Type: INFJ
Posts: ''


index: 165396
Type: INFJ
Posts: ''


index: 176206
Type: INTP
Posts: ''


index: 176207
Type: INTP
Posts: ''


index: 176208
Type: INTP
Posts: ''


index: 176209
Type: INTP
Posts: ''


index: 176210
Type: INTP
Posts: ''


index: 176211
Type: INTP
Posts: ''


index: 176212
Type: INTP
Posts: ''


index: 176214
Type: INTP
Posts: ''


index: 176215
Type: INTP
Posts: ''


index: 176216
Type: INTP
Posts: ''


index: 176217
Type: INTP
Posts: ''


index: 176218
Type: INTP
Posts: ''


index: 176219
Type: INTP
Posts: ''


index: 176220
Type: INTP
Posts: ''


index: 176222
Type: INTP
Posts: ''


index: 176223
Type: INTP
Posts: ''


index: 176224
Type: INTP
Posts: ''


index: 176225
Type: INTP
Posts: ''


index: 179840
Type: INTJ
Posts: ''


index: 179841
Type: INTJ
Posts: ''


index: 179842
Type: INTJ
Posts: ''


index: 179843
Type: INTJ
Posts: ''


index: 179845
Type: INTJ
Posts: ''


index: 179846
Type: INTJ
Posts: ''


index: 182191

In [11]:
exploded_data = exploded_data.dropna(subset=["posts"])
exploded_data = exploded_data[exploded_data["posts"].str.strip() != ""]
exploded_data.head()

   type                                              posts
0  INFJ        'http://www.youtube.com/watch?v=qsXHcwe3krw
1  INFJ  http://41.media.tumblr.com/tumblr_lfouy03PMA1q...
2  INFJ  enfp and intj moments  https://www.youtube.com...
3  INFJ  What has been the most life-changing experienc...
4  INFJ  http://www.youtube.com/watch?v=vXZeYwwRDw8   h...

In [12]:
exploded_data.shape

(421757, 2)

In [13]:
exploded_data["type"].value_counts()

type
INFP    89595
INFJ    71948
INTP    63251
INTJ    52406
ENTP    33544
ENFP    32610
ISTP    16454
ISFP    12971
ENTJ    11235
ISTJ     9870
ENFJ     9283
ISFJ     8114
ESTP     4329
ESFP     2213
ESFJ     2018
ESTJ     1916
Name: count, dtype: int64

In [14]:
exploded_data["type"].value_counts(normalize=True)*100

type
INFP    21.243275
INFJ    17.059112
INTP    14.997024
INTJ    12.425638
ENTP     7.953395
ENFP     7.731940
ISTP     3.901299
ISFP     3.075468
ENTJ     2.663856
ISTJ     2.340210
ENFJ     2.201030
ISFJ     1.923857
ESTP     1.026420
ESFP     0.524710
ESFJ     0.478475
ESTJ     0.454290
Name: proportion, dtype: float64

* i increased number of data points for all which 
* will this lead to better learning for small classes after increasing its samples?

In [15]:
from sklearn.base import BaseEstimator, TransformerMixin
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
import re
import contractions
from nltk.tokenize import word_tokenize

class Clean_Text(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.lemmetizer = WordNetLemmatizer()
        self.stop_words = set(stopwords.words("english"))
        
    def fit(self, X, y=None):
        return self
    
    def transform(self, X: pd.Series):
        X =  X.copy()
        X_transformed = X.apply(self.Cleaner)
        return X_transformed
    
    def Cleaner(self, text):
        text = re.sub(r'http[s]?://\S+', '', str(text)).lower()
        text = contractions.fix(text)
        text = re.sub(r'[^a-z\s]', ' ', text)
        text = re.sub(r'\s+', ' ', text).strip()
        tokens = word_tokenize(text)
        tokens = [self.lemmetizer.lemmatize(word) for word in tokens if word not in self.stop_words]
        return ' '.join(tokens)

In [16]:
from sklearn.pipeline import Pipeline
test_pipeline = Pipeline([
    ("clean_text", Clean_Text())
])
cleaned_post_test = test_pipeline.fit_transform(exploded_data["posts"])
cleaned_post_test.shape

(421757,)

In [17]:
cleaned_post_test.head()

0
1
2    enfp intj moment sportscenter top ten play prank
3                       life changing experience life
4                                        repeat today
Name: posts, dtype: object

In [18]:
empty_data = cleaned_post_test[cleaned_post_test.str.strip() == ""]
empty_data.shape

(13887,)

In [19]:
exploded_data["Cleaned_Posts"] = cleaned_post_test
exploded_data.head()

,type,posts,Cleaned_Posts
0,INFJ,'http://www.youtube.com/watch?v=qsXHcwe3krw,
1,INFJ,http://41.media.tumblr.com/tumblr_lfouy03PMA1q...,
2,INFJ,enfp and intj moments https://www.youtube.com...,enfp intj moment sportscenter top ten play prank
3,INFJ,What has been the most life-changing experienc...,life changing experience life
4,INFJ,http://www.youtube.com/watch?v=vXZeYwwRDw8 h...,repeat today

In [20]:
final_cleaned_data = exploded_data[exploded_data["Cleaned_Posts"].str.strip() != ""].reset_index(drop=True)
final_cleaned_data.head()

,type,posts,Cleaned_Posts
0,INFJ,enfp and intj moments https://www.youtube.com...,enfp intj moment sportscenter top ten play prank
1,INFJ,What has been the most life-changing experienc...,life changing experience life
2,INFJ,http://www.youtube.com/watch?v=vXZeYwwRDw8 h...,repeat today
3,INFJ,May the PerC Experience immerse you.,may perc experience immerse
4,INFJ,The last thing my INFJ friend posted on his fa...,last thing infj friend posted facebook committ...

In [21]:
final_cleaned_data.isnull().sum()

type             0
posts            0
Cleaned_Posts    0
dtype: int64

In [22]:
empty_rows = final_cleaned_data[final_cleaned_data["Cleaned_Posts"].str.strip() == ""]
print(empty_rows)

Empty DataFrame
Columns: [type, posts, Cleaned_Posts]
Index: []

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(final_cleaned_data["Cleaned_Posts"], final_cleaned_data["type"], test_size=0.2, random_state=42, stratify=final_cleaned_data["type"], shuffle=True)
X_train, X_valid, y_train, y_valid = train_test_split(X_train, y_train, test_size=0.2, random_state=42, stratify=y_train, shuffle=True)
print(f"Train: {X_train.shape[0]} samples")
print(f"Validation: {X_valid.shape[0]} samples")
print(f"Test: {X_test.shape[0]} samples")

Train: 261036 samples
Validation: 65260 samples
Test: 81574 samples

In [24]:
import torch.nn as nn

class GRU_Model(nn.Module):
    def __init__(self, vocab_size, emb_dim, hidden_dim, num_classes, num_layers=1):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, emb_dim)
        self.gru = nn.GRU(emb_dim, hidden_dim, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_dim, num_classes)
        self.RLU = nn.ReLU()
        
    def forward(self, x):
        embedd = self.embedding(x)
        gru_output, hidden = self.gru(embedd)
        output = self.RLU(gru_output[:, -1, :])
        output = self.fc(output)
        return output

In [25]:
from collections import Counter

all_text = " ".join(final_cleaned_data["Cleaned_Posts"])
word_counts = Counter(all_text.split())
frequent_words = [word for word, count in word_counts.items() if count >= 3]
print(f"Number of unique words: {len(word_counts)}")
print(f"Unique words after filtering: {len(frequent_words)}")

Number of unique words: 88766
Unique words after filtering: 35123

In [26]:
vocab = ["<PAD>", "<UNK>"] + frequent_words
vocab_size = len(vocab)
w2i = {word: idx for idx, word in enumerate(vocab)}
i2w = {idx: word for idx, word in enumerate(vocab)}
print(f"index for pad is:{w2i['<PAD>']}\nindex for unk is:{w2i['<UNK>']}\n")
print(f"index of 100 its word is:{i2w[99]}")

index for pad is:0
index for unk is:1

index of 100 its word is:late

In [27]:
import torch
from sklearn.base import BaseEstimator, TransformerMixin
class TextToVector(BaseEstimator, TransformerMixin):
    def __init__(self, w2i, max_len):
        self.w2i = w2i
        self.max_len = max_len
    
    def fit(self, X, y=None):
        return self
    
    def encode_pad_seq(self, seq):
        encoded = [self.w2i.get(word, self.w2i["<UNK>"]) for word in str(seq).split()]
        
        if len(encoded) > self.max_len:
            return encoded[:self.max_len]
         
        elif len(encoded) < self.max_len:
            return encoded + [self.w2i["<PAD>"]] * (self.max_len - len(encoded))
        else:
            return encoded
    
    def transform(self, X):
        encoded = X.apply(self.encode_pad_seq)
        encoded_list = encoded.tolist()
        return torch.tensor(encoded_list, dtype=torch.long)

In [28]:
final_pipeline = Pipeline([
    ("cleaner", Clean_Text()),
    ("vectorizer", TextToVector(w2i, max_len=100))
])
final_pipeline.fit(X_train)
X_train_vectorized = final_pipeline.transform(X_train)
X_train_vectorized.shape

d:\anaconda\envs\iti-nlp\lib\site-packages\sklearn\pipeline.py:61: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(

torch.Size([261036, 100])

In [29]:
X_valid_vectorized = final_pipeline.transform(X_valid)
X_valid_vectorized.shape

d:\anaconda\envs\iti-nlp\lib\site-packages\sklearn\pipeline.py:61: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(

torch.Size([65260, 100])

In [30]:
X_test_vectorized = final_pipeline.transform(X_test)
X_test_vectorized.shape

d:\anaconda\envs\iti-nlp\lib\site-packages\sklearn\pipeline.py:61: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(

torch.Size([81574, 100])

In [32]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_valid_encoded = label_encoder.transform(y_valid)
y_test_encoded = label_encoder.transform(y_test)
print(f"Encoded labels: {label_encoder.classes_}")
print(f"length is: {len(label_encoder.classes_)}")

Encoded labels: ['ENFJ' 'ENFP' 'ENTJ' 'ENTP' 'ESFJ' 'ESFP' 'ESTJ' 'ESTP' 'INFJ' 'INFP'
 'INTJ' 'INTP' 'ISFJ' 'ISFP' 'ISTJ' 'ISTP']
length is: 16

In [33]:
y_train_encoded = torch.tensor(y_train_encoded, dtype=torch.long)
y_valid_encoded = torch.tensor(y_valid_encoded, dtype=torch.long)
y_test_encoded = torch.tensor(y_test_encoded, dtype=torch.long)

In [34]:
from torch.utils.data import TensorDataset, DataLoader
train_dataset = TensorDataset(X_train_vectorized, y_train_encoded)
valid_dataset = TensorDataset(X_valid_vectorized, y_valid_encoded)
test_dataset = TensorDataset(X_test_vectorized, y_test_encoded)

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
valid_loader = DataLoader(valid_dataset, batch_size=64, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

In [35]:
import torch.optim as optim
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

In [36]:
criterion = nn.CrossEntropyLoss()
model = GRU_Model(vocab_size=vocab_size, emb_dim=100, hidden_dim=128, num_classes=len(label_encoder.classes_))
optimizer = optim.Adam(model.parameters(), lr=0.001)

for i in range(10):
    model.train()
    total_loss = 0
    for X_batch, y_batch in train_loader:
        X_batch, y_batch = X_batch.to(device), y_batch.to(device)
        optimizer.zero_grad()
        outputs = model(X_batch)
        loss = criterion(outputs, y_batch)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    avg_loss = total_loss / len(train_loader)
    
    model.eval()
    val_loss = 0
    with torch.no_grad():
        for batch_x, batch_y in valid_loader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            outputs = model(batch_x)
            loss = criterion(outputs, batch_y)
            val_loss += loss.item()
    print(f"Epoch {i+1}, Loss: {avg_loss:.4f}, Val Loss: {val_loss:.4f}")

Epoch 1, Loss: 2.2770, Val Loss: 2285.7567
Epoch 2, Loss: 2.1984, Val Loss: 2219.0073
Epoch 3, Loss: 2.1397, Val Loss: 2216.3681

KeyboardInterrupt: